camel:
  springboot:
    name: ssl-client
#  component:
#    http.ssl-context-parameters: clientConfig
management:
  endpoint:
    camelroutes:
      enabled: true
      read-only: true
    health.enabled: true
  endpoints.web.exposure.include: info,health,camelroutes
