spring:
  ssl.bundle:
    jks:
      server:
        key:
          alias: "server"
        keystore:
          location: "classpath:server.jks"
          password: "pass123"
          type: "PKCS12"
server:
  port: 8443
  ssl:
    bundle: "server"
    #client-auth: NEED
    client-auth: NONE
    #client-auth: WANT
camel:
  springboot:
    name: ssl-server
management:
  endpoint:
    camelroutes:
      enabled: true
      read-only: true
    health.enabled: true
  endpoints.web.exposure.include: info,health,camelroutes
