camel:
  springboot:
    name: ssl-client
#  component:
#    http:
#      ssl-context-parameters: clientConfig
#      use-global-ssl-context-parameters: true
management:
  endpoint:
    camelroutes:
      enabled: true
      read-only: true
    health.enabled: true
  endpoints.web.exposure.include: info,health,camelroutes

logging:
  level:
    org.apache.camel.support.jsse: TRACE


